#!/bin/sh -e

mkdir -p \
    "/usr/lib/firefox/distribution"

cat vendor.js >> "/usr/lib/firefox/browser/defaults/preferences/vendor.js"
cp -f policies.json "/usr/lib/firefox/distribution/"

echo done
